[package]
name = "imgconv"
version = "0.1.0"
edition = "2021"
default-run = "imgconv"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
image = "0.25.1"
rayon = "1.10.0"
webp = "0.3.0"

[[bin]]
name = "imgconv"
path = "src/main.rs"

[[bin]]
name = "cleanup"
path = "src/bin/cleanup.rs"
